=== eemeyer/discovery_datatool/src/docroot/WEB-INF/classes/datatool-config-3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://transparensee.com/schema/datatool-config-3"
    xmlns:tns="http://transparensee.com/schema/datatool-config-3"
    elementFormDefault="qualified"
    >

    <element name="config" type="tns:ConfigType"/>

    <complexType name="ConfigType">
      <sequence>
        <element name="accessControl" type="tns:AccessControlType" minOccurs="0" maxOccurs="1"/>
        <element name="dataSources" type="tns:DataSourcesType"/>
        <element name="profiles" type="tns:ProfilesType"/>
        <element name="publishers" type="tns:PublishersType"/>
      </sequence>
    </complexType>

    <complexType name="AccessControlType">
      <annotation>
        <documentation xml:lang="en">
          Optional restrict feed access using basic HTTP authentication.
          Since datatool-config-3.
          By adding the element, you turn on basic HTTP authentication.
          Add child user elements.
        </documentation>
      </annotation>
      <sequence minOccurs="0">
        <element name="user">
          <complexType>
            <attribute name="name" type="string" use="required"/>
            <attribute name="password" type="string" use="required"/>
          </complexType>
        </element>
      </sequence>
    </complexType>

    <complexType name="DataSourcesType">
      <sequence minOccurs="1" maxOccurs="unbounded">
        <choice>
          <element name="dataSource" type="tns:DataSourceType"/>
          <element name="driver" type="tns:DriverType"/>
        </choice>
      </sequence>
    </complexType>

    <complexType name="DataSourceType">
      <sequence minOccurs="0" maxOccurs="unbounded">
        <any processContents="lax"/>
      </sequence>
      <attribute name="name" type="string" use="required"/>
      <attribute name="jar" type="string" use="optional"/>
      <attribute name="class" type="string" use="required"/>
    </complexType>

    <complexType name="DriverType">
      <sequence>
        <element name="url"/>
        <element name="username" minOccurs="0"/>
        <element name="password" minOccurs="0"/>
        <element name="properties" minOccurs="0">
          <complexType>
            <sequence minOccurs="0" maxOccurs="unbounded">
              <any processContents="lax"/>
            </sequence>
          </complexType>
        </element>
      </sequence>
      <attribute name="name" type="string" use="required"/>
      <attribute name="jar" type="string" use="optional"/>
      <attribute name="class" type="string" use="required"/>
    </complexType>

    <complexType name="ProfilesType">
      <sequence minOccurs="1" maxOccurs="unbounded">
        <element name="sqlProfile" type="tns:SqlProfileType"/>
      </sequence>
    </complexType>

    <complexType name="PublishersType">
      <sequence minOccurs="1" maxOccurs="unbounded">
        <element name="sqlPublisher" type="tns:SqlPublisherType"/>
      </sequence>
    </complexType>

    <complexType name="SqlProfileType">
      <sequence>
        <element name="createSql" type="string" minOccurs="0">
          <annotation>
            <documentation xml:lang="en">
              Optional SQL used to create a profile when one is not found.
              Since datatool-config-2.
              Bound parameters:
                :name -- profile name
              Outputs:
                none
            </documentation>
          </annotation>
        </element>
        <element name="retrieveSql" type="tns:retrieveSql"/>
        <element name="updateSql" type="string"/>
      </sequence>
      <attribute name="name" type="string" use="required"/>
      <attribute name="dataSource" type="string" use="required"/>
    </complexType>

    <complexType name="retrieveSql" mixed="true">
      <attribute name="startColumn" use="required"/>
      <attribute name="endColumn" use="required"/>
    </complexType>

    <complexType name="SqlPublisherType">
      <sequence minOccurs="1" maxOccurs="unbounded">
        <element name="action" type="tns:ActionType"/>
      </sequence>
      <attribute name="name" type="string" use="required"/>
      <attribute name="dataSource" type="string" use="required"/>
      <attribute name="profile" type="string" use="required"/>
    </complexType>

    <complexType name="ActionType">
      <sequence>
        <element name="query" type="string"/>
      </sequence>
      <attribute name="type" type="tns:ActionTypeType" use="required"/>
      <attribute name="filter" type="tns:FilterActionType" use="optional"/>
      <attribute name="idColumn" type="string" use="required"/>
      <attribute name="jsonColumnNames" type="string"  use="optional"/>
    </complexType>

    <simpleType name="ActionTypeType">
      <restriction base="string">
        <enumeration value="create"/>
        <enumeration value="delete"/>
      </restriction>
    </simpleType>

    <simpleType name="FilterActionType">
      <restriction base="string">
        <enumeration value="delta"/>
        <enumeration value="snapshot"/>
      </restriction>
    </simpleType>
</schema>

=== eemeyer/discovery_datatool/stage/examples/v3/sqlserver-driver.xml
<config
  xmlns="http://transparensee.com/schema/datatool-config-3"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation=
    "http://transparensee.com/schema/datatool-config-3
     http://transparensee.com/schema/datatool-config-3.xsd">
  <dataSources>
    <driver name="production-dataSource"
      jar="drivers/jtds-1.2.5.jar"
      class="net.sourceforge.jtds.jdbc.Driver">
      <url>jdbc:jtds:sqlserver://localhost/test</url>
      <username>test</username>
      <password>test</password>
    </driver>
  </dataSources>

  <profiles>
    <sqlProfile name="production-profile" dataSource="production-dataSource">
      <retrieveSql startColumn="start" endColumn="end">
        select last_run as start, CURRENT_TIMESTAMP as end
        from changeset_profile
        where name = :name
      </retrieveSql>
      <updateSql>
        update changeset_profile
        set last_run = :lastRun
        where name = :name
      </updateSql>
    </sqlProfile>
  </profiles>

  <publishers>
    <sqlPublisher name="production"
      dataSource="production-dataSource" profile="production-profile">
      <action type="create" filter="delta" idColumn="id">
        <query><![CDATA[
          select * from items
          where last_updated >= :start and last_updated < :end
        ]]></query>
      </action>
      <action type="delete" filter="delta" idColumn="id">
        <query><![CDATA[
          select id from deleted_items
          where last_updated >= :start and last_updated < :end
        ]]></query>
      </action>
      <action type="create" filter="snapshot" idColumn="id">
        <query><![CDATA[
          select * from items
          where last_updated < :end
        ]]></query>
      </action>
    </sqlPublisher>
  </publishers>
</config>
