=== eemeyer/discovery_datatool/src/docroot/WEB-INF/classes/datatool-config-4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://transparensee.com/schema/datatool-config-4"
    xmlns:tns="http://transparensee.com/schema/datatool-config-4"
    elementFormDefault="qualified"
    >

    <element name="config" type="tns:ConfigType"/>

    <complexType name="ConfigType">
      <sequence>
        <element name="accessControl" type="tns:AccessControlType" minOccurs="0" maxOccurs="1"/>
        <element name="dataSources" type="tns:DataSourcesType"/>
        <element name="profiles" type="tns:ProfilesType"/>
        <element name="publishers" type="tns:PublishersType"/>
      </sequence>
    </complexType>

    <complexType name="AccessControlType">
      <annotation>
        <documentation xml:lang="en">
          Optional restrict feed access using basic HTTP authentication.
          Since datatool-config-3.
          By adding the element, you turn on basic HTTP authentication.
          Add child user elements.
        </documentation>
      </annotation>
      <sequence minOccurs="0">
        <element name="user">
          <complexType>
            <attribute name="name" type="string" use="required"/>
            <attribute name="password" type="string" use="required"/>
          </complexType>
        </element>
      </sequence>
    </complexType>

    <complexType name="DataSourcesType">
      <sequence minOccurs="1" maxOccurs="unbounded">
        <choice>
          <element name="dataSource" type="tns:DataSourceType"/>
          <element name="driver" type="tns:DriverType"/>
        </choice>
      </sequence>
    </complexType>

    <complexType name="DataSourceType">
      <sequence minOccurs="0" maxOccurs="unbounded">
        <any processContents="lax"/>
      </sequence>
      <attribute name="name" type="string" use="required"/>
      <attribute name="jar" type="string" use="optional"/>
      <attribute name="class" type="string" use="required"/>
    </complexType>

    <complexType name="DriverType">
      <sequence>
        <element name="url"/>
        <element name="username" minOccurs="0"/>
        <element name="password" minOccurs="0"/>
        <element name="properties" minOccurs="0">
          <complexType>
            <sequence minOccurs="0" maxOccurs="unbounded">
              <any processContents="lax"/>
            </sequence>
          </complexType>
        </element>
      </sequence>
      <attribute name="name" type="string" use="required"/>
      <attribute name="jar" type="string" use="optional"/>
      <attribute name="class" type="string" use="required"/>
    </complexType>

    <complexType name="ProfilesType">
      <sequence minOccurs="1" maxOccurs="unbounded">
        <element name="sqlProfile" type="tns:SqlProfileType"/>
      </sequence>
    </complexType>

    <complexType name="PublishersType">
      <sequence minOccurs="1" maxOccurs="unbounded">
        <choice minOccurs="1" maxOccurs="unbounded">
          <element name="sqlPublisher" type="tns:SqlPublisherType"/>
          <element name="createItemOnlySqlPublisher" type="tns:CreateItemOnlySqlPublisherType"/>
        </choice>
      </sequence>
    </complexType>

    <complexType name="SqlProfileType">
      <sequence>
        <element name="createSql" type="string" minOccurs="0">
          <annotation>
            <documentation xml:lang="en">
              Optional SQL used to create a profile when one is not found.
              Since datatool-config-2.
              Bound parameters:
                :name -- profile name
              Outputs:
                none
            </documentation>
          </annotation>
        </element>
        <element name="retrieveSql" type="tns:retrieveSql"/>
        <element name="updateSql" type="string"/>
      </sequence>
      <attribute name="name" type="string" use="required"/>
      <attribute name="dataSource" type="string" use="required"/>
    </complexType>

    <complexType name="retrieveSql" mixed="true">
      <attribute name="startColumn" use="required"/>
      <attribute name="endColumn" use="required"/>
    </complexType>

    <complexType name="SqlPublisherTypeBase" abstract="true">
      <attribute name="name" type="string" use="required"/>
      <attribute name="dataSource" type="string" use="required"/>
      <attribute name="profile" type="string" use="required"/>
    </complexType>

    <complexType name="SqlPublisherType">
      <complexContent>
        <extension base="tns:SqlPublisherTypeBase">
          <sequence minOccurs="1" maxOccurs="unbounded">
            <element name="action" type="tns:ActionType"/>
          </sequence>
        </extension>
      </complexContent>
    </complexType>

    <complexType name="CreateItemOnlySqlPublisherType">
      <complexContent>
        <extension base="tns:SqlPublisherTypeBase">
          <sequence minOccurs="1" maxOccurs="unbounded">
            <element name="action" type="tns:CreateItemOnlyActionType"/>
          </sequence>
          <attribute name="type" type="tns:CreateItemOnlySqlPublisherTypeType" use="required"/>
        </extension>
      </complexContent>
    </complexType>

    <complexType name="ActionTypeBase" abstract="true">
      <sequence>
        <element name="query" type="string"/>
        <element name="subquery" type="tns:SubQueryType" minOccurs="0" maxOccurs="unbounded"/>
      </sequence>
      <attribute name="idColumn" type="string" use="required"/>
      <attribute name="jsonColumnNames" type="string"  use="optional"/>
    </complexType>

    <complexType name="ActionType">
      <complexContent>
        <extension base="tns:ActionTypeBase">
          <annotation>
            <documentation xml:lang="en">
              Each action with a matching filter is run in sequence.
            </documentation>
          </annotation>
          <attribute name="type" type="tns:ActionTypeType" use="required"/>
          <attribute name="filter" type="tns:FilterActionType" use="optional"/>
        </extension>
      </complexContent>
    </complexType>

    <complexType name="CreateItemOnlyActionType">
      <complexContent>
        <extension base="tns:ActionTypeBase">
          <annotation>
            <documentation xml:lang="en">
              Each action with a matching filter is run in sequence.
            </documentation>
          </annotation>
        </extension>
      </complexContent>
    </complexType>

    <complexType name="SubQueryType">
      <simpleContent>
        <extension base="string">
      <attribute name="delimiter" type="string" use="optional" />
      <attribute name="field" type="string" />
      <attribute name="type" type="tns:SubQueryTypeType" default="array" />
        </extension>
      </simpleContent>
    </complexType>

    <simpleType name="SubQueryTypeType">
      <restriction base="string">
        <enumeration value="array"/>
        <enumeration value="delimited"/>
      </restriction>
    </simpleType>

    <simpleType name="ActionTypeType">
      <restriction base="string">
        <enumeration value="create"/>
        <enumeration value="delete"/>
      </restriction>
    </simpleType>

    <simpleType name="CreateItemOnlySqlPublisherTypeType">
      <restriction base="string">
        <enumeration value="bulk"/>
        <enumeration value="full"/>
        <enumeration value="snapshot"/>
      </restriction>
    </simpleType>

    <simpleType name="FilterActionType">
      <restriction base="string">
        <enumeration value="delta"/>
        <enumeration value="snapshot"/>
      </restriction>
    </simpleType>
</schema>

=== eemeyer/discovery_datatool/src/test/java/com/t11e/discovery/datatool/BulkAndFullChangesetTest.xml
<config
  xmlns="http://transparensee.com/schema/datatool-config-4"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation=
    "http://transparensee.com/schema/datatool-config-4
     http://transparensee.com/schema/datatool-config-4.xsd">
  <dataSources>
    <driver name="dataSource"
      class="org.apache.derby.jdbc.EmbeddedDriver">
      <url>jdbc:derby:memory:test;create=true</url>
    </driver>
  </dataSources>

  <profiles>
    <sqlProfile name="sqlProfile" dataSource="dataSource">
      <retrieveSql startColumn="startTime" endColumn="endTime">
        select lastRun as startTime, CURRENT_TIMESTAMP as endTime from BulkAndFullChangesetTestProfile where name = :name
      </retrieveSql>
      <updateSql>
        update BulkAndFullChangesetTestProfile set lastRun = :lastRun where name = :name
      </updateSql>
    </sqlProfile>
  </profiles>

  <publishers>
    <createItemOnlySqlPublisher name="test-bulk" dataSource="dataSource" profile="sqlProfile" type="bulk">
      <action idColumn="id">
        <query><![CDATA[
          select * from IntegrationContent where lastUpdated < :end
        ]]></query>
      </action>
    </createItemOnlySqlPublisher>
    <createItemOnlySqlPublisher name="test-full" dataSource="dataSource" profile="sqlProfile" type="full">
      <action idColumn="id">
        <query><![CDATA[
          select * from IntegrationContent where lastUpdated < :end
        ]]></query>
      </action>
    </createItemOnlySqlPublisher>
    <createItemOnlySqlPublisher name="test-create-snapshot" dataSource="dataSource" profile="sqlProfile" type="snapshot">
      <action idColumn="id">
        <query><![CDATA[
          select * from IntegrationContent where lastUpdated < :end
        ]]></query>
      </action>
    </createItemOnlySqlPublisher>
    <sqlPublisher name="test-snapshot" dataSource="dataSource" profile="sqlProfile">
      <action type="create" filter="snapshot" idColumn="id">
        <query>
          select * from IntegrationContent
        </query>
      </action>
      <action type="delete" filter="snapshot" idColumn="id">
        <query>
          select id from IntegrationDeleted
        </query>
      </action>
    </sqlPublisher>
  </publishers>
</config>

=== eemeyer/discovery_datatool/stage/examples/v4/sqlserver-driver.xml
<config
  xmlns="http://transparensee.com/schema/datatool-config-4"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation=
    "http://transparensee.com/schema/datatool-config-4
     http://transparensee.com/schema/datatool-config-4.xsd">
  <dataSources>
    <driver name="production-dataSource"
      jar="drivers/jtds-1.2.5.jar"
      class="net.sourceforge.jtds.jdbc.Driver">
      <url>jdbc:jtds:sqlserver://localhost/test</url>
      <username>test</username>
      <password>test</password>
    </driver>
  </dataSources>

  <profiles>
    <sqlProfile name="production-profile" dataSource="production-dataSource">
      <retrieveSql startColumn="start" endColumn="end">
        select last_run as start, CURRENT_TIMESTAMP as end
        from changeset_profile
        where name = :name
      </retrieveSql>
      <updateSql>
        update changeset_profile
        set last_run = :lastRun
        where name = :name
      </updateSql>
    </sqlProfile>
  </profiles>

  <publishers>
    <sqlPublisher name="production"
      dataSource="production-dataSource" profile="production-profile">
      <snapshot>
        <set-item idColumn="id">
          <query><![CDATA[
            select * from items
          ]]></query>
          <subquery field="color-default"><![CDATA[
            select name from SubqueryColors where parent_id=:id order by name
          ]]></subquery>
          <subquery field="color-array" type="array"><![CDATA[
            select name from SubqueryColors where parent_id=:id order by name
          ]]></subquery>
          <subquery field="color-delimited" type="delimited"><![CDATA[
            select name from SubqueryColors where parent_id=:id order by name
          ]]></subquery>
          <subquery field="color-delimited" type="delimited" delimiter="|"><![CDATA[
            select name from SubqueryColors where parent_id=:id order by name
          ]]></subquery>
        </set-item>
      </snapshot>
      <delta>
        <set-item idColumn="id">
          <!--
          The following bound parameters are available to the query:
          :start - The inclusive start of the date range for this changeset as a java.util.Date.
          :end - The exclusive end of the date range for this changeset as a java.util.Date.
          :kind - "snapshot" or "delta"
           -->
          <query><![CDATA[
            select * from items
            where last_updated >= :start and last_updated < :end
          ]]></query>
          <!--
            Each action of type "create" can contain zero or more subquery elements.
            Each subquery must return only a single column.
            If a subquery returns more than one column, a run-time exception is thrown, and the changeset will fail to be created.
            The field attribute specifies the field name to use when creating the changeset set-item entry.
            Properties returned in the main query can be replaced by subquery values by using an overlapping field name.
            The default subquery type is "array" - which builds an array in the set-item structure for the multiple values.
            The other type option value is "delimited" - which builds a single delimited string containing the multiple values.
            An optional delimiter can specified. If none is specified, then the delimiter defaults to a comma.
            All the columns returned by the main query are available to the subquery as named bound parameters
            (:start, :end, and :kind are not available to the subquery).
            The subquery examples below use the id returned from the main query as a bound parameter.
           -->
          <subquery field="color-default"><![CDATA[
            select name from SubqueryColors where parent_id=:id order by name
          ]]></subquery>
          <subquery field="color-array" type="array"><![CDATA[
            select name from SubqueryColors where parent_id=:id order by name
          ]]></subquery>
          <subquery field="color-delimited" type="delimited"><![CDATA[
            select name from SubqueryColors where parent_id=:id order by name
          ]]></subquery>
          <subquery field="color-delimited" type="delimited" delimiter="|"><![CDATA[
            select name from SubqueryColors where parent_id=:id order by name
          ]]></subquery>
        </set-item>
        <remove-item idColumn="id">
          <query><![CDATA[
            select id from deleted_items
            where last_updated >= :start and last_updated < :end
          ]]></query>
        </remove-item>
      </delta>
    </sqlPublisher>
  </publishers>
</config>

=== eemeyer/discovery_datatool/src/config/configuration-test.xml
<config
  xmlns="http://transparensee.com/schema/datatool-config-4"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation=
    "http://transparensee.com/schema/datatool-config-4
     http://transparensee.com/schema/datatool-config-4.xsd">
  <dataSources>
    <dataSource name="mysqlTest"
      jar="stage/mysql-connector-java-5.1.10-bin.jar"
      class="com.mysql.jdbc.jdbc2.optional.MysqlDataSource">
      <url>jdbc:mysql://localhost/test</url>
      <user>test<span>hello</span></user>
      <password>test</password>
    </dataSource>
  </dataSources>

  <profiles>
    <sqlProfile name="sqlProfile" dataSource="mysqlTest">
      <!-- createSql is optional. By including it we enable automatic profile creation. -->
      <createSql>
        insert into changeset_profile (name) values (:name)
      </createSql>
      <retrieveSql startColumn="start" endColumn="end">
        select last_run as start, CURRENT_TIMESTAMP as end
        from changeset_profile
        where name = :name
      </retrieveSql>
      <updateSql>
        update changeset_profile
        set last_run = :lastRun
        where name = :name
      </updateSql>
    </sqlProfile>
  </profiles>

  <publishers>
    <sqlPublisher name="test" dataSource="mysqlTest" profile="sqlProfile">
      <action type="create" filter="delta"
              idColumn="id" jsonColumnNames="jsonColumn">
        <query><![CDATA[
          select * from Content
          where last_updated >= :start and last_updated < :end
        ]]></query>
        <!-- type="delimited" must only return a single column, or the pull will fail with an exception -->
        <subquery property="categories" type="delimited" delimiter=","><![CDATA[
          select name from content_category inner join Content on content_category._content_id=:id
        ]]></subquery>
        <subquery property="categories_array" type="array"><![CDATA[
          select name from content_category inner join Content on content_category._content_id=:id
        ]]></subquery>
      </action>
      <action type="create" filter="snapshot"
              idColumn="id" jsonColumnNames="data">
        <query>select * from Content</query>
      </action>
    </sqlPublisher>
  </publishers>
</config>

=== eemeyer/discovery_datatool/stage/examples/v4/mysql-datasource.xml
<config
  xmlns="http://transparensee.com/schema/datatool-config-4"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation=
    "http://transparensee.com/schema/datatool-config-4
     http://transparensee.com/schema/datatool-config-4.xsd">
  <!--
    Please see the Discovery Engine online documentation for complete details about configuring the Data Tool:
    https://transparensee.com/docs/discovery/current/html/data_integration/datatool.html
  -->
  <dataSources>
    <dataSource name="production-dataSource"
      jar="drivers/mysql-connector-java-5.1.10-bin.jar"
      class="com.mysql.jdbc.jdbc2.optional.MysqlDataSource">
      <url>jdbc:mysql://localhost/test</url>
      <user>test</user>
      <password>test</password>
    </dataSource>
  </dataSources>

  <profiles>
    <sqlProfile name="production-profile" dataSource="production-dataSource">
      <retrieveSql startColumn="start" endColumn="end">
        select last_run as start, CURRENT_TIMESTAMP as end
        from changeset_profile
        where name = :name
      </retrieveSql>
      <updateSql>
        update changeset_profile
        set last_run = :lastRun
        where name = :name
      </updateSql>
    </sqlProfile>
  </profiles>

  <publishers>
    <sqlPublisher name="production"
      dataSource="production-dataSource" profile="production-profile">
      <snapshot>
        <set-item idColumn="id">
          <query><![CDATA[
            select * from items
          ]]></query>
          <subquery><![CDATA[
            select name as color from SubqueryColors where parent_id=:id order by name
          ]]></subquery>
          <subquery property="color-array" type="array"><![CDATA[
            select name from SubqueryColors where parent_id=:id order by name
          ]]></subquery>
          <subquery property="color-delimited" type="delimited"><![CDATA[
            select name from SubqueryColors where parent_id=:id order by name
          ]]></subquery>
          <subquery property="color-delimited" type="delimited" delimiter="|"><![CDATA[
            select name from SubqueryColors where parent_id=:id order by name
          ]]></subquery>
          <subquery property="address" discriminator="addr_type"><![CDATA[
            select addr_type, street, city, state, zipcode from SubqueryAddress where parent_id=:id order by id
          ]]></subquery>
          <subquery propertyPrefix="product"><![CDATA[
            select id, price, description from order_lines where order_id=:id order by id
          ]]></subquery>
        </set-item>
      </snapshot>
      <delta>
        <set-item idColumn="id">
          <!--
          The following bound parameters are available to the query:
          :start - The inclusive start of the date range for this changeset as a java.util.Date.
          :end - The exclusive end of the date range for this changeset as a java.util.Date.
          :kind - "snapshot" or "delta"
           -->
          <query><![CDATA[
            select * from items
            where last_updated >= :start and last_updated < :end
          ]]></query>
          <subquery><![CDATA[
            select name as color from SubqueryColors where parent_id=:id order by name
          ]]></subquery>
          <subquery property="color-array" type="array"><![CDATA[
            select name from SubqueryColors where parent_id=:id order by name
          ]]></subquery>
          <subquery property="color-delimited" type="delimited"><![CDATA[
            select name from SubqueryColors where parent_id=:id order by name
          ]]></subquery>
          <subquery property="color-delimited" type="delimited" delimiter="|"><![CDATA[
            select name from SubqueryColors where parent_id=:id order by name
          ]]></subquery>
          <subquery property="address" discriminator="addr_type"><![CDATA[
            select addr_type, street, city, state, zipcode from SubqueryAddress where parent_id=:id order by id
          ]]></subquery>
          <subquery property="products"><![CDATA[
            select id, price, description from order_lines where order_id=:id order by id
          ]]></subquery>
        </set-item>
        <remove-item idColumn="id">
          <query><![CDATA[
            select id from deleted_items
            where last_updated >= :start and last_updated < :end
          ]]></query>
        </remove-item>
      </delta>
    </sqlPublisher>
  </publishers>
</config>
